import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:syncfusion_flutter_pdf/pdf.dart';

import '../models/financial_report.dart';
import '../services/currency_provider.dart';

abstract final class PdfReportService {
  static final _green = PdfColor(68, 198, 105);
  static final _ink = PdfColor(0, 0, 0);
  static final _gray = PdfColor(94, 94, 94);
  static final _field = PdfColor(224, 255, 233);
  static final _red = PdfColor(240, 76, 76);
  static final _white = PdfColor(255, 255, 255);
  static const _logoAssetPath =
      'android/app/src/main/res/drawable/spendant_notification_large_icon.png';

  static const _channel = MethodChannel('spendant_flutter/platform_config');

  static Future<String?> generate(FinancialReport report) async {
    if (kIsWeb) return null;
    try {
      final bytes = await _buildPdf(report);
      return await _save(report, bytes);
    } catch (error) {
      debugPrint('PdfReportService.generate failed: $error');
      return null;
    }
  }

  static Future<void> openFile(String path) async {
    if (kIsWeb) return;
    try {
      await _channel.invokeMethod<void>('openFile', {'path': path});
    } catch (error) {
      debugPrint('PdfReportService.openFile failed: $error');
    }
  }

  static Future<Uint8List> _buildPdf(FinancialReport report) async {
    final doc = PdfDocument();
    final iso = CurrencyProvider.instance.activeCurrency;
    final logo = await _loadLogo();

    final boldFont = PdfStandardFont(
      PdfFontFamily.helvetica,
      12,
      style: PdfFontStyle.bold,
    );
    final titleFont = PdfStandardFont(
      PdfFontFamily.helvetica,
      20,
      style: PdfFontStyle.bold,
    );
    final secFont = PdfStandardFont(
      PdfFontFamily.helvetica,
      11,
      style: PdfFontStyle.bold,
    );
    final bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 10);
    final smallFont = PdfStandardFont(PdfFontFamily.helvetica, 9);
    final tinyFont = PdfStandardFont(PdfFontFamily.helvetica, 8);

    PdfPage curPage = doc.pages.add();
    PdfGraphics g = curPage.graphics;
    double w = curPage.getClientSize().width;
    double pageH = curPage.getClientSize().height;
    double y = 0;

    void drawHeader() {
      g.drawRectangle(
        brush: PdfSolidBrush(_green),
        bounds: Rect.fromLTWH(0, 0, w, 76),
      );

      if (logo != null) {
        g.drawImage(logo, Rect.fromLTWH(12, 10, 54, 54));
      } else {
        g.drawString(
          'S',
          PdfStandardFont(
            PdfFontFamily.helvetica,
            28,
            style: PdfFontStyle.bold,
          ),
          brush: PdfSolidBrush(_white),
          bounds: Rect.fromLTWH(12, 10, 54, 54),
          format: PdfStringFormat(
            alignment: PdfTextAlignment.center,
            lineAlignment: PdfVerticalAlignment.middle,
          ),
        );
      }

      g.drawString(
        'SpendAnt',
        PdfStandardFont(PdfFontFamily.helvetica, 22, style: PdfFontStyle.bold),
        brush: PdfSolidBrush(_white),
        bounds: Rect.fromLTWH(74, 12, 200, 28),
      );
      g.drawString(
        'Financial Report',
        PdfStandardFont(PdfFontFamily.helvetica, 10),
        brush: PdfSolidBrush(_white),
        bounds: Rect.fromLTWH(74, 40, 200, 16),
      );
      g.drawString(
        report.periodLabel,
        boldFont,
        brush: PdfSolidBrush(_white),
        bounds: Rect.fromLTWH(w - 200, 26, 192, 22),
        format: PdfStringFormat(alignment: PdfTextAlignment.right),
      );
    }

    void drawFooter(PdfPage page) {
      final fg = page.graphics;
      final fw = page.getClientSize().width;
      final fh = page.getClientSize().height;
      fg.drawLine(
        PdfPen(PdfColor(208, 208, 208)),
        Offset(0, fh - 22),
        Offset(fw, fh - 22),
      );
      fg.drawString(
        'Generated by SpendAnt  |  ${DateFormat('MMM d, y | HH:mm').format(report.generatedAt)}',
        smallFont,
        brush: PdfSolidBrush(_gray),
        bounds: Rect.fromLTWH(0, fh - 16, fw, 14),
        format: PdfStringFormat(alignment: PdfTextAlignment.center),
      );
    }

    void addPage() {
      curPage = doc.pages.add();
      g = curPage.graphics;
      w = curPage.getClientSize().width;
      pageH = curPage.getClientSize().height;
      drawHeader();
      y = 88;
    }

    void ensureSpace(double needed) {
      if (y + needed > pageH - 30) addPage();
    }

    drawHeader();
    y = 88;

    g.drawRectangle(
      brush: PdfSolidBrush(_field),
      bounds: Rect.fromLTWH(0, y, w, 58),
    );
    g.drawString(
      'Total Spent',
      bodyFont,
      brush: PdfSolidBrush(_gray),
      bounds: Rect.fromLTWH(16, y + 8, 200, 14),
    );
    g.drawString(
      '$iso ${_fmt(report.totalSpent)}',
      titleFont,
      brush: PdfSolidBrush(_ink),
      bounds: Rect.fromLTWH(16, y + 22, w - 32, 28),
    );
    y += 70;

    if (report.dailySpends.isNotEmpty) {
      ensureSpace(120);
      g.drawString(
        'Daily Spending',
        secFont,
        brush: PdfSolidBrush(_ink),
        bounds: Rect.fromLTWH(0, y, w, 16),
      );
      y += 20;
      const histH = 70.0;
      _drawHistogram(
        g,
        report.dailySpends,
        Rect.fromLTWH(0, y, w, histH),
        smallFont,
        tinyFont,
      );
      y += histH + 18;
    }

    if (report.topExpenses.isNotEmpty) {
      ensureSpace(22 + report.topExpenses.length * 54.0 + 8);
      g.drawString(
        'Top Expenses',
        secFont,
        brush: PdfSolidBrush(_ink),
        bounds: Rect.fromLTWH(0, y, w, 16),
      );
      y += 20;
      for (final e in report.topExpenses) {
        final amountText = '$iso ${_fmt(e.amount)}';
        const leftPadding = 10.0;
        const rightPadding = 10.0;
        const amountWidth = 110.0;
        const topPadding = 8.0;
        const bottomPadding = 8.0;
        const lineHeight = 16.0;
        final nameWidth = w - leftPadding - rightPadding - amountWidth - 12;
        final metaText =
            '${_cleanLabel(e.category)}  |  ${DateFormat('MMM d, y').format(e.date)}';
        final nameLines = _wrapText(
          _safeExpenseName(e.name),
          boldFont,
          nameWidth,
          maxLines: 2,
        );
        final rowHeight =
            (topPadding +
                    (nameLines.length * lineHeight) +
                    4 +
                    lineHeight +
                    bottomPadding)
                .clamp(52.0, 72.0);
        ensureSpace(rowHeight + 2);
        g.drawRectangle(
          brush: PdfSolidBrush(_field),
          bounds: Rect.fromLTWH(0, y, w, rowHeight),
        );
        for (var i = 0; i < nameLines.length; i++) {
          g.drawString(
            nameLines[i],
            boldFont,
            brush: PdfSolidBrush(_ink),
            bounds: Rect.fromLTWH(
              leftPadding,
              y + topPadding + (i * lineHeight),
              nameWidth,
              lineHeight + 2,
            ),
            format: PdfStringFormat(lineAlignment: PdfVerticalAlignment.top),
          );
        }
        g.drawString(
          metaText,
          smallFont,
          brush: PdfSolidBrush(_gray),
          bounds: Rect.fromLTWH(
            leftPadding,
            y + rowHeight - bottomPadding - lineHeight,
            nameWidth,
            lineHeight,
          ),
        );
        g.drawString(
          amountText,
          boldFont,
          brush: PdfSolidBrush(_red),
          bounds: Rect.fromLTWH(
            w - amountWidth - rightPadding,
            y,
            amountWidth,
            rowHeight,
          ),
          format: PdfStringFormat(
            alignment: PdfTextAlignment.right,
            lineAlignment: PdfVerticalAlignment.middle,
          ),
        );
        y += rowHeight + 2;
      }
      y += 8;
    }

    if (report.topCategories.isNotEmpty) {
      ensureSpace(22 + report.topCategories.length * 22.0 + 8);
      g.drawString(
        'Top Categories',
        secFont,
        brush: PdfSolidBrush(_ink),
        bounds: Rect.fromLTWH(0, y, w, 16),
      );
      y += 20;
      final maxAmt = report.topCategories.first.amount;
      final barClrs = [
        PdfColor(68, 198, 105),
        PdfColor(74, 211, 245),
        PdfColor(184, 125, 233),
        PdfColor(255, 136, 110),
        PdfColor(189, 221, 52),
      ];
      for (var i = 0; i < report.topCategories.length; i++) {
        final cat = report.topCategories[i];
        final frac = maxAmt > 0 ? (cat.amount / maxAmt).clamp(0.0, 1.0) : 0.0;
        final amountText = '$iso ${_fmt(cat.amount)}';
        const labelWidth = 126.0;
        const amountWidth = 92.0;
        const gapAfterAmount = 12.0;
        final barX = labelWidth + amountWidth + gapAfterAmount;
        final barW = (w - barX) * frac;
        g.drawString(
          cat.label,
          bodyFont,
          brush: PdfSolidBrush(_ink),
          bounds: Rect.fromLTWH(0, y, labelWidth, 14),
        );
        g.drawString(
          amountText,
          smallFont,
          brush: PdfSolidBrush(_gray),
          bounds: Rect.fromLTWH(labelWidth, y, amountWidth, 14),
        );
        if (barW > 0) {
          g.drawRectangle(
            brush: PdfSolidBrush(barClrs[i % barClrs.length]),
            bounds: Rect.fromLTWH(barX, y + 2, barW, 10),
          );
        }
        y += 22;
      }
      y += 8;
    }

    final allInsights = [
      ...report.bqInsights,
      if (report.reportsGeneratedCount > 0)
        'Report #${report.reportsGeneratedCount} generated by you'
            '${report.mostActiveWeekday != null ? '  |  Most active day: ${_wd(report.mostActiveWeekday!)}' : ''}',
    ];
    if (allInsights.isNotEmpty) {
      ensureSpace(20 + allInsights.length * 14.0 + 8);
      g.drawString(
        'Insights',
        secFont,
        brush: PdfSolidBrush(_ink),
        bounds: Rect.fromLTWH(0, y, w, 16),
      );
      y += 18;
      for (final insight in allInsights) {
        ensureSpace(14);
        g.drawString(
          '- $insight',
          smallFont,
          brush: PdfSolidBrush(_gray),
          bounds: Rect.fromLTWH(4, y, w - 8, 13),
        );
        y += 14;
      }
    }

    for (var i = 0; i < doc.pages.count; i++) {
      drawFooter(doc.pages[i]);
    }

    final bytes = Uint8List.fromList(doc.saveSync());
    doc.dispose();
    return bytes;
  }

  static void _drawHistogram(
    PdfGraphics g,
    List<DailySpend> days,
    Rect bounds,
    PdfFont labelFont,
    PdfFont tinyFont,
  ) {
    if (days.isEmpty) return;
    final maxAmt = days.fold<double>(0, (m, d) => d.amount > m ? d.amount : m);
    const labelH = 14.0;
    final chartH = bounds.height - labelH;
    final gap = bounds.width / days.length;
    final barW = gap * 0.65;

    for (var i = 0; i < days.length; i++) {
      final barH = maxAmt > 0 ? (days[i].amount / maxAmt) * chartH : 0.0;
      final x = bounds.left + i * gap + (gap - barW) / 2;
      final yTop = bounds.top + chartH - barH;

      if (barH > 0) {
        g.drawRectangle(
          brush: PdfSolidBrush(PdfColor(68, 198, 105)),
          bounds: Rect.fromLTWH(x, yTop, barW, barH),
        );
      }

      final step = (days.length / 6).ceil().clamp(1, 99);
      if (i % step == 0) {
        final label = DateFormat('d').format(days[i].date);
        g.drawString(
          label,
          tinyFont,
          brush: PdfSolidBrush(PdfColor(94, 94, 94)),
          bounds: Rect.fromLTWH(
            x + barW / 2 - 8,
            bounds.top + chartH + 2,
            16,
            12,
          ),
          format: PdfStringFormat(alignment: PdfTextAlignment.center),
        );
      }
    }
  }

  static Future<String?> _save(FinancialReport report, Uint8List bytes) async {
    final String dir = Platform.isAndroid
        ? '/storage/emulated/0/Download'
        : '/tmp';
    final folder = Directory(dir);
    if (!folder.existsSync()) folder.createSync(recursive: true);
    final ts = DateFormat('yyyyMMdd_HHmm').format(report.generatedAt);
    final file = File(p.join(dir, 'SpendAnt_Report_$ts.pdf'));
    await file.writeAsBytes(bytes);
    return file.path;
  }

  static String _fmt(double v) {
    if (v >= 1000) return NumberFormat('#,###', 'en_US').format(v.round());
    return v
        .toStringAsFixed(v == v.roundToDouble() ? 0 : 2)
        .replaceAll(RegExp(r'\.?0+$'), '');
  }

  static Future<PdfBitmap?> _loadLogo() async {
    try {
      final data = await rootBundle.load(_logoAssetPath);
      return PdfBitmap(data.buffer.asUint8List());
    } catch (error) {
      debugPrint('PdfReportService._loadLogo failed: $error');
      return null;
    }
  }

  static List<String> _wrapText(
    String text,
    PdfFont font,
    double maxWidth, {
    int maxLines = 1,
  }) {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    if (normalized.isEmpty) return const ['-'];

    final words = normalized.split(' ');
    final lines = <String>[];
    var current = '';
    var wordIndex = 0;

    for (; wordIndex < words.length; wordIndex++) {
      final word = words[wordIndex];
      final candidate = current.isEmpty ? word : '$current $word';
      if (font.measureString(candidate).width <= maxWidth || current.isEmpty) {
        current = candidate;
        continue;
      }

      lines.add(current);
      current = word;
      if (lines.length == maxLines - 1) {
        break;
      }
    }

    final remaining = [
      if (current.isNotEmpty) current,
      if (wordIndex + 1 < words.length) ...words.skip(wordIndex + 1),
    ].join(' ').trim();

    if (remaining.isNotEmpty) {
      lines.add(remaining);
    }

    if (lines.isEmpty) lines.add(normalized);
    if (lines.length > maxLines) lines.removeRange(maxLines, lines.length);

    final lastIndex = lines.length - 1;
    final wasTrimmed = wordIndex + 1 < words.length;
    if (wasTrimmed || font.measureString(lines[lastIndex]).width > maxWidth) {
      lines[lastIndex] = _ellipsize(lines[lastIndex], font, maxWidth);
    }

    return lines;
  }

  static String _ellipsize(String text, PdfFont font, double maxWidth) {
    const ellipsis = '...';
    var value = text.trim();
    while (value.isNotEmpty &&
        font.measureString('$value$ellipsis').width > maxWidth) {
      value = value.substring(0, value.length - 1).trimRight();
    }
    return value.isEmpty ? ellipsis : '$value$ellipsis';
  }

  static String _cleanLabel(String value) {
    final trimmed = value.trim();
    return trimmed.isEmpty ? 'Uncategorized' : trimmed;
  }

  static String _safeExpenseName(String value) {
    final trimmed = value.trim();
    return trimmed.isEmpty ? 'Unnamed expense' : trimmed;
  }

  static String _wd(int d) {
    const n = ['', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    return d >= 1 && d <= 7 ? n[d] : '';
  }
}
