// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw9W_7GwOntgGVTqYpnSj8k7_9_W-7zWU',
    appId: '1:306562030190:web:ab00bd17d79b70ebb9a47f',
    messagingSenderId: '306562030190',
    projectId: 'spendant-5ec40',
    authDomain: 'spendant-5ec40.firebaseapp.com',
    storageBucket: 'spendant-5ec40.firebasestorage.app',
    measurementId: 'G-ED2B883J88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2qJ2TxEtjaeNFP9GiJbPHYE1oEVTDso',
    appId: '1:306562030190:android:69311013ddf518f5b9a47f',
    messagingSenderId: '306562030190',
    projectId: 'spendant-5ec40',
    storageBucket: 'spendant-5ec40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARbiX-wPTfWwiiPLYalrzhh_42KaiLPds',
    appId: '1:306562030190:ios:f31765d51588e391b9a47f',
    messagingSenderId: '306562030190',
    projectId: 'spendant-5ec40',
    storageBucket: 'spendant-5ec40.firebasestorage.app',
    iosBundleId: 'com.example.spendantFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARbiX-wPTfWwiiPLYalrzhh_42KaiLPds',
    appId: '1:306562030190:ios:f31765d51588e391b9a47f',
    messagingSenderId: '306562030190',
    projectId: 'spendant-5ec40',
    storageBucket: 'spendant-5ec40.firebasestorage.app',
    iosBundleId: 'com.example.spendantFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw9W_7GwOntgGVTqYpnSj8k7_9_W-7zWU',
    appId: '1:306562030190:web:f48a22d0dbe4bf72b9a47f',
    messagingSenderId: '306562030190',
    projectId: 'spendant-5ec40',
    authDomain: 'spendant-5ec40.firebaseapp.com',
    storageBucket: 'spendant-5ec40.firebasestorage.app',
    measurementId: 'G-6MBD3021VL',
  );
}
